services:
  app:
    image: nomi-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    command: ["yarn", "start"]
    environment:
      - "NODE_ENV=production"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next